# mkdocs.yml
site_name: InspireFace
site_url: https://example.com/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
      nav_translations:
        zh:
          Getting Started: 开始使用
          API Reference: API 参考
          Examples: 示例
          Guides: 指南

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation:
      - release: getting-started/installation/release.md
      - compile: getting-started/installation/compile.md
      - docker: getting-started/installation/docker.md
  - Features:
    - cross-platform: features/cross-platform.md
    - face recognition: features/face-recognition.md
    - feature hub: features/feature-hub.md
  - Guides:
    - basic: guides/basic.md
    - unit-test: guides/unit-test.md
    - switch-cv-backend: guides/switch-cv-backend.md
    - cmake-options: guides/cmake-options.md
    - benchmark: guides/benchmark.md